# Generated by Django 4.1.5 on 2023-04-27 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gifted', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='created_by',
        ),
    ]
