# Generated by Django 4.1.5 on 2023-01-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifted', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Features'},
        ),
        migrations.RemoveField(
            model_name='feature',
            name='size',
        ),
        migrations.AlterField(
            model_name='feature',
            name='slug',
            field=models.SlugField(default='small', max_length=255),
        ),
    ]
