# Generated by Django 4.1.5 on 2023-01-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifted', '0003_feature_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='slug',
            field=models.SlugField(default='features', max_length=255),
        ),
    ]
