# Generated by Django 4.1.5 on 2023-02-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifted', '0006_alter_feature_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='size',
            field=models.CharField(choices=[('small', 'SMALL'), ('large', 'LARGE')], default='small', max_length=5),
        ),
    ]
